# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: .
# Target is a subdirs project 

QT += widgets

SUBDIRS += src \
           plugins

TEMPLATE = subdirs 
CONFIG += release \
          warn_on \
          qt \
          thread 
