# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./plugins
# Target is a subdirs project 

target.path = /usr/local/lib/qtscope/plugins
TEMPLATE = subdirs
CONFIG += release \
warn_on
SUBDIRS += xtplot \
           dummy \
           xyplot 
