Document: qtscope
Title: Debian qtscope Manual
Author: <insert document author here>
Abstract: This manual describes what qtscope is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/qtscope/qtscope.sgml.gz

Format: postscript
Files: /usr/share/doc/qtscope/qtscope.ps.gz

Format: text
Files: /usr/share/doc/qtscope/qtscope.text.gz

Format: HTML
Index: /usr/share/doc/qtscope/html/index.html
Files: /usr/share/doc/qtscope/html/*.html

  
